apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-7mby
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-mkek-tenant/rhtap-demo-app/hacbs-test-project-7mby@sha256:4f7139bcd53f9a446b6a8109269222672737242fc6f3b971a4853a436653e49c
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
